// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=mock_speech/mock_speech.go -package=mock_speech
//

// Package mock_speech is a generated GoMock package.
package mock_speech

import (
	context "context"
	reflect "reflect"

	core "github.com/josephnhtam/live-agent-go/voice/internal/core"
	speech "github.com/josephnhtam/live-agent-go/voice/internal/speech"
	gomock "go.uber.org/mock/gomock"
)

// MockRecognitionHandler is a mock of RecognitionHandler interface.
type MockRecognitionHandler struct {
	ctrl     *gomock.Controller
	recorder *MockRecognitionHandlerMockRecorder
	isgomock struct{}
}

// MockRecognitionHandlerMockRecorder is the mock recorder for MockRecognitionHandler.
type MockRecognitionHandlerMockRecorder struct {
	mock *MockRecognitionHandler
}

// NewMockRecognitionHandler creates a new mock instance.
func NewMockRecognitionHandler(ctrl *gomock.Controller) *MockRecognitionHandler {
	mock := &MockRecognitionHandler{ctrl: ctrl}
	mock.recorder = &MockRecognitionHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecognitionHandler) EXPECT() *MockRecognitionHandlerMockRecorder {
	return m.recorder
}

// OnInterim mocks base method.
func (m *MockRecognitionHandler) OnInterim() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnInterim")
}

// OnInterim indicates an expected call of OnInterim.
func (mr *MockRecognitionHandlerMockRecorder) OnInterim() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnInterim", reflect.TypeOf((*MockRecognitionHandler)(nil).OnInterim))
}

// OnSpeechEnd mocks base method.
func (m *MockRecognitionHandler) OnSpeechEnd() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnSpeechEnd")
}

// OnSpeechEnd indicates an expected call of OnSpeechEnd.
func (mr *MockRecognitionHandlerMockRecorder) OnSpeechEnd() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnSpeechEnd", reflect.TypeOf((*MockRecognitionHandler)(nil).OnSpeechEnd))
}

// OnSpeechRecognized mocks base method.
func (m *MockRecognitionHandler) OnSpeechRecognized(transcripts []core.Transcript) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnSpeechRecognized", transcripts)
}

// OnSpeechRecognized indicates an expected call of OnSpeechRecognized.
func (mr *MockRecognitionHandlerMockRecorder) OnSpeechRecognized(transcripts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnSpeechRecognized", reflect.TypeOf((*MockRecognitionHandler)(nil).OnSpeechRecognized), transcripts)
}

// OnSpeechStart mocks base method.
func (m *MockRecognitionHandler) OnSpeechStart() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnSpeechStart")
}

// OnSpeechStart indicates an expected call of OnSpeechStart.
func (mr *MockRecognitionHandlerMockRecorder) OnSpeechStart() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnSpeechStart", reflect.TypeOf((*MockRecognitionHandler)(nil).OnSpeechStart))
}

// MockVAD is a mock of VAD interface.
type MockVAD struct {
	ctrl     *gomock.Controller
	recorder *MockVADMockRecorder
	isgomock struct{}
}

// MockVADMockRecorder is the mock recorder for MockVAD.
type MockVADMockRecorder struct {
	mock *MockVAD
}

// NewMockVAD creates a new mock instance.
func NewMockVAD(ctrl *gomock.Controller) *MockVAD {
	mock := &MockVAD{ctrl: ctrl}
	mock.recorder = &MockVADMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVAD) EXPECT() *MockVADMockRecorder {
	return m.recorder
}

// Event mocks base method.
func (m *MockVAD) Event() <-chan speech.VADEvent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Event")
	ret0, _ := ret[0].(<-chan speech.VADEvent)
	return ret0
}

// Event indicates an expected call of Event.
func (mr *MockVADMockRecorder) Event() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Event", reflect.TypeOf((*MockVAD)(nil).Event))
}

// Feed mocks base method.
func (m *MockVAD) Feed(ctx context.Context, frame core.AudioFrame) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Feed", ctx, frame)
	ret0, _ := ret[0].(error)
	return ret0
}

// Feed indicates an expected call of Feed.
func (mr *MockVADMockRecorder) Feed(ctx, frame any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Feed", reflect.TypeOf((*MockVAD)(nil).Feed), ctx, frame)
}

// Start mocks base method.
func (m *MockVAD) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockVADMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockVAD)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockVAD) Stop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockVADMockRecorder) Stop(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockVAD)(nil).Stop), ctx)
}

// MockTranscriber is a mock of Transcriber interface.
type MockTranscriber struct {
	ctrl     *gomock.Controller
	recorder *MockTranscriberMockRecorder
	isgomock struct{}
}

// MockTranscriberMockRecorder is the mock recorder for MockTranscriber.
type MockTranscriberMockRecorder struct {
	mock *MockTranscriber
}

// NewMockTranscriber creates a new mock instance.
func NewMockTranscriber(ctrl *gomock.Controller) *MockTranscriber {
	mock := &MockTranscriber{ctrl: ctrl}
	mock.recorder = &MockTranscriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranscriber) EXPECT() *MockTranscriberMockRecorder {
	return m.recorder
}

// Feed mocks base method.
func (m *MockTranscriber) Feed(ctx context.Context, frame core.AudioFrame) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Feed", ctx, frame)
	ret0, _ := ret[0].(error)
	return ret0
}

// Feed indicates an expected call of Feed.
func (mr *MockTranscriberMockRecorder) Feed(ctx, frame any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Feed", reflect.TypeOf((*MockTranscriber)(nil).Feed), ctx, frame)
}

// Start mocks base method.
func (m *MockTranscriber) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockTranscriberMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockTranscriber)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockTranscriber) Stop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockTranscriberMockRecorder) Stop(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockTranscriber)(nil).Stop), ctx)
}

// Transcribe mocks base method.
func (m *MockTranscriber) Transcribe() <-chan core.Transcript {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transcribe")
	ret0, _ := ret[0].(<-chan core.Transcript)
	return ret0
}

// Transcribe indicates an expected call of Transcribe.
func (mr *MockTranscriberMockRecorder) Transcribe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transcribe", reflect.TypeOf((*MockTranscriber)(nil).Transcribe))
}
