// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=mock_voice/mock_voice.go -package=mock_voice
//

// Package mock_voice is a generated GoMock package.
package mock_voice

import (
	context "context"
	reflect "reflect"

	voice "github.com/josephnhtam/live-agent-go/voice"
	audio "github.com/josephnhtam/live-agent-go/voice/audio"
	gomock "go.uber.org/mock/gomock"
)

// MockDialogTools is a mock of DialogTools interface.
type MockDialogTools struct {
	ctrl     *gomock.Controller
	recorder *MockDialogToolsMockRecorder
	isgomock struct{}
}

// MockDialogToolsMockRecorder is the mock recorder for MockDialogTools.
type MockDialogToolsMockRecorder struct {
	mock *MockDialogTools
}

// NewMockDialogTools creates a new mock instance.
func NewMockDialogTools(ctrl *gomock.Controller) *MockDialogTools {
	mock := &MockDialogTools{ctrl: ctrl}
	mock.recorder = &MockDialogToolsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDialogTools) EXPECT() *MockDialogToolsMockRecorder {
	return m.recorder
}

// AddFiller mocks base method.
func (m *MockDialogTools) AddFiller(token voice.Token) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddFiller", token)
}

// AddFiller indicates an expected call of AddFiller.
func (mr *MockDialogToolsMockRecorder) AddFiller(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFiller", reflect.TypeOf((*MockDialogTools)(nil).AddFiller), token)
}

// PlayAudio mocks base method.
func (m *MockDialogTools) PlayAudio(wave *audio.Wave, opts *audio.Options) (audio.Handle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlayAudio", wave, opts)
	ret0, _ := ret[0].(audio.Handle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PlayAudio indicates an expected call of PlayAudio.
func (mr *MockDialogToolsMockRecorder) PlayAudio(wave, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlayAudio", reflect.TypeOf((*MockDialogTools)(nil).PlayAudio), wave, opts)
}

// SetInterruptible mocks base method.
func (m *MockDialogTools) SetInterruptible(interruptible bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetInterruptible", interruptible)
}

// SetInterruptible indicates an expected call of SetInterruptible.
func (mr *MockDialogToolsMockRecorder) SetInterruptible(interruptible any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetInterruptible", reflect.TypeOf((*MockDialogTools)(nil).SetInterruptible), interruptible)
}

// MockBrain is a mock of Brain interface.
type MockBrain struct {
	ctrl     *gomock.Controller
	recorder *MockBrainMockRecorder
	isgomock struct{}
}

// MockBrainMockRecorder is the mock recorder for MockBrain.
type MockBrainMockRecorder struct {
	mock *MockBrain
}

// NewMockBrain creates a new mock instance.
func NewMockBrain(ctrl *gomock.Controller) *MockBrain {
	mock := &MockBrain{ctrl: ctrl}
	mock.recorder = &MockBrainMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrain) EXPECT() *MockBrainMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockBrain) Generate(ctx context.Context, prompt string, tools voice.DialogTools, tokens chan<- voice.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", ctx, prompt, tools, tokens)
	ret0, _ := ret[0].(error)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockBrainMockRecorder) Generate(ctx, prompt, tools, tokens any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockBrain)(nil).Generate), ctx, prompt, tools, tokens)
}

// MockSynthesizer is a mock of Synthesizer interface.
type MockSynthesizer struct {
	ctrl     *gomock.Controller
	recorder *MockSynthesizerMockRecorder
	isgomock struct{}
}

// MockSynthesizerMockRecorder is the mock recorder for MockSynthesizer.
type MockSynthesizerMockRecorder struct {
	mock *MockSynthesizer
}

// NewMockSynthesizer creates a new mock instance.
func NewMockSynthesizer(ctrl *gomock.Controller) *MockSynthesizer {
	mock := &MockSynthesizer{ctrl: ctrl}
	mock.recorder = &MockSynthesizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSynthesizer) EXPECT() *MockSynthesizerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockSynthesizer) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSynthesizerMockRecorder) Close(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSynthesizer)(nil).Close), ctx)
}

// SampleRate mocks base method.
func (m *MockSynthesizer) SampleRate() int32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SampleRate")
	ret0, _ := ret[0].(int32)
	return ret0
}

// SampleRate indicates an expected call of SampleRate.
func (mr *MockSynthesizerMockRecorder) SampleRate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SampleRate", reflect.TypeOf((*MockSynthesizer)(nil).SampleRate))
}

// Synthesize mocks base method.
func (m *MockSynthesizer) Synthesize(ctx context.Context, tokens <-chan voice.Token, arg2 chan<- voice.AudioFrame) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Synthesize", ctx, tokens, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Synthesize indicates an expected call of Synthesize.
func (mr *MockSynthesizerMockRecorder) Synthesize(ctx, tokens, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Synthesize", reflect.TypeOf((*MockSynthesizer)(nil).Synthesize), ctx, tokens, arg2)
}

// MockVAD is a mock of VAD interface.
type MockVAD struct {
	ctrl     *gomock.Controller
	recorder *MockVADMockRecorder
	isgomock struct{}
}

// MockVADMockRecorder is the mock recorder for MockVAD.
type MockVADMockRecorder struct {
	mock *MockVAD
}

// NewMockVAD creates a new mock instance.
func NewMockVAD(ctrl *gomock.Controller) *MockVAD {
	mock := &MockVAD{ctrl: ctrl}
	mock.recorder = &MockVADMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVAD) EXPECT() *MockVADMockRecorder {
	return m.recorder
}

// Event mocks base method.
func (m *MockVAD) Event() <-chan voice.VADEvent {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Event")
	ret0, _ := ret[0].(<-chan voice.VADEvent)
	return ret0
}

// Event indicates an expected call of Event.
func (mr *MockVADMockRecorder) Event() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Event", reflect.TypeOf((*MockVAD)(nil).Event))
}

// Feed mocks base method.
func (m *MockVAD) Feed(ctx context.Context, frame voice.AudioFrame) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Feed", ctx, frame)
	ret0, _ := ret[0].(error)
	return ret0
}

// Feed indicates an expected call of Feed.
func (mr *MockVADMockRecorder) Feed(ctx, frame any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Feed", reflect.TypeOf((*MockVAD)(nil).Feed), ctx, frame)
}

// Start mocks base method.
func (m *MockVAD) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockVADMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockVAD)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockVAD) Stop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockVADMockRecorder) Stop(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockVAD)(nil).Stop), ctx)
}

// MockTranscriber is a mock of Transcriber interface.
type MockTranscriber struct {
	ctrl     *gomock.Controller
	recorder *MockTranscriberMockRecorder
	isgomock struct{}
}

// MockTranscriberMockRecorder is the mock recorder for MockTranscriber.
type MockTranscriberMockRecorder struct {
	mock *MockTranscriber
}

// NewMockTranscriber creates a new mock instance.
func NewMockTranscriber(ctrl *gomock.Controller) *MockTranscriber {
	mock := &MockTranscriber{ctrl: ctrl}
	mock.recorder = &MockTranscriberMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTranscriber) EXPECT() *MockTranscriberMockRecorder {
	return m.recorder
}

// Feed mocks base method.
func (m *MockTranscriber) Feed(ctx context.Context, frame voice.AudioFrame) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Feed", ctx, frame)
	ret0, _ := ret[0].(error)
	return ret0
}

// Feed indicates an expected call of Feed.
func (mr *MockTranscriberMockRecorder) Feed(ctx, frame any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Feed", reflect.TypeOf((*MockTranscriber)(nil).Feed), ctx, frame)
}

// Start mocks base method.
func (m *MockTranscriber) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockTranscriberMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockTranscriber)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockTranscriber) Stop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockTranscriberMockRecorder) Stop(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockTranscriber)(nil).Stop), ctx)
}

// Transcribe mocks base method.
func (m *MockTranscriber) Transcribe() <-chan voice.Transcript {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Transcribe")
	ret0, _ := ret[0].(<-chan voice.Transcript)
	return ret0
}

// Transcribe indicates an expected call of Transcribe.
func (mr *MockTranscriberMockRecorder) Transcribe() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Transcribe", reflect.TypeOf((*MockTranscriber)(nil).Transcribe))
}

// MockSession is a mock of Session interface.
type MockSession struct {
	ctrl     *gomock.Controller
	recorder *MockSessionMockRecorder
	isgomock struct{}
}

// MockSessionMockRecorder is the mock recorder for MockSession.
type MockSessionMockRecorder struct {
	mock *MockSession
}

// NewMockSession creates a new mock instance.
func NewMockSession(ctrl *gomock.Controller) *MockSession {
	mock := &MockSession{ctrl: ctrl}
	mock.recorder = &MockSessionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSession) EXPECT() *MockSessionMockRecorder {
	return m.recorder
}

// AudioIn mocks base method.
func (m *MockSession) AudioIn() <-chan voice.AudioFrame {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AudioIn")
	ret0, _ := ret[0].(<-chan voice.AudioFrame)
	return ret0
}

// AudioIn indicates an expected call of AudioIn.
func (mr *MockSessionMockRecorder) AudioIn() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AudioIn", reflect.TypeOf((*MockSession)(nil).AudioIn))
}

// Close mocks base method.
func (m *MockSession) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSessionMockRecorder) Close(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSession)(nil).Close), ctx)
}

// Connected mocks base method.
func (m *MockSession) Connected() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Connected")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Connected indicates an expected call of Connected.
func (mr *MockSessionMockRecorder) Connected() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Connected", reflect.TypeOf((*MockSession)(nil).Connected))
}

// Done mocks base method.
func (m *MockSession) Done() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Done")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Done indicates an expected call of Done.
func (mr *MockSessionMockRecorder) Done() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Done", reflect.TypeOf((*MockSession)(nil).Done))
}

// MessageIn mocks base method.
func (m *MockSession) MessageIn() <-chan string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageIn")
	ret0, _ := ret[0].(<-chan string)
	return ret0
}

// MessageIn indicates an expected call of MessageIn.
func (mr *MockSessionMockRecorder) MessageIn() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageIn", reflect.TypeOf((*MockSession)(nil).MessageIn))
}

// MessageReady mocks base method.
func (m *MockSession) MessageReady() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MessageReady")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// MessageReady indicates an expected call of MessageReady.
func (mr *MockSessionMockRecorder) MessageReady() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MessageReady", reflect.TypeOf((*MockSession)(nil).MessageReady))
}

// SendAudio mocks base method.
func (m *MockSession) SendAudio(frame voice.AudioFrame, pacing bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAudio", frame, pacing)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAudio indicates an expected call of SendAudio.
func (mr *MockSessionMockRecorder) SendAudio(frame, pacing any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAudio", reflect.TypeOf((*MockSession)(nil).SendAudio), frame, pacing)
}

// SendMessage mocks base method.
func (m *MockSession) SendMessage(text string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendMessage", text)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendMessage indicates an expected call of SendMessage.
func (mr *MockSessionMockRecorder) SendMessage(text any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendMessage", reflect.TypeOf((*MockSession)(nil).SendMessage), text)
}

// MockRealtimeModel is a mock of RealtimeModel interface.
type MockRealtimeModel struct {
	ctrl     *gomock.Controller
	recorder *MockRealtimeModelMockRecorder
	isgomock struct{}
}

// MockRealtimeModelMockRecorder is the mock recorder for MockRealtimeModel.
type MockRealtimeModelMockRecorder struct {
	mock *MockRealtimeModel
}

// NewMockRealtimeModel creates a new mock instance.
func NewMockRealtimeModel(ctrl *gomock.Controller) *MockRealtimeModel {
	mock := &MockRealtimeModel{ctrl: ctrl}
	mock.recorder = &MockRealtimeModelMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRealtimeModel) EXPECT() *MockRealtimeModelMockRecorder {
	return m.recorder
}

// AudioOut mocks base method.
func (m *MockRealtimeModel) AudioOut() <-chan voice.AudioFrame {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AudioOut")
	ret0, _ := ret[0].(<-chan voice.AudioFrame)
	return ret0
}

// AudioOut indicates an expected call of AudioOut.
func (mr *MockRealtimeModelMockRecorder) AudioOut() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AudioOut", reflect.TypeOf((*MockRealtimeModel)(nil).AudioOut))
}

// Done mocks base method.
func (m *MockRealtimeModel) Done() <-chan error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Done")
	ret0, _ := ret[0].(<-chan error)
	return ret0
}

// Done indicates an expected call of Done.
func (mr *MockRealtimeModelMockRecorder) Done() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Done", reflect.TypeOf((*MockRealtimeModel)(nil).Done))
}

// PromptOut mocks base method.
func (m *MockRealtimeModel) PromptOut() <-chan voice.Prompt {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PromptOut")
	ret0, _ := ret[0].(<-chan voice.Prompt)
	return ret0
}

// PromptOut indicates an expected call of PromptOut.
func (mr *MockRealtimeModelMockRecorder) PromptOut() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PromptOut", reflect.TypeOf((*MockRealtimeModel)(nil).PromptOut))
}

// SendAudio mocks base method.
func (m *MockRealtimeModel) SendAudio(ctx context.Context, frame voice.AudioFrame) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAudio", ctx, frame)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendAudio indicates an expected call of SendAudio.
func (mr *MockRealtimeModelMockRecorder) SendAudio(ctx, frame any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAudio", reflect.TypeOf((*MockRealtimeModel)(nil).SendAudio), ctx, frame)
}

// Start mocks base method.
func (m *MockRealtimeModel) Start(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockRealtimeModelMockRecorder) Start(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockRealtimeModel)(nil).Start), ctx)
}

// Stop mocks base method.
func (m *MockRealtimeModel) Stop(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stop", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Stop indicates an expected call of Stop.
func (mr *MockRealtimeModelMockRecorder) Stop(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockRealtimeModel)(nil).Stop), ctx)
}

// TokenOut mocks base method.
func (m *MockRealtimeModel) TokenOut() <-chan voice.Token {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TokenOut")
	ret0, _ := ret[0].(<-chan voice.Token)
	return ret0
}

// TokenOut indicates an expected call of TokenOut.
func (mr *MockRealtimeModelMockRecorder) TokenOut() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TokenOut", reflect.TypeOf((*MockRealtimeModel)(nil).TokenOut))
}
