// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=mock_dialog/mock_dialog.go -package=mock_dialog
//

// Package mock_dialog is a generated GoMock package.
package mock_dialog

import (
	context "context"
	reflect "reflect"

	audio "github.com/josephnhtam/live-agent-go/voice/audio"
	core "github.com/josephnhtam/live-agent-go/voice/internal/core"
	dialog "github.com/josephnhtam/live-agent-go/voice/internal/dialog"
	gomock "go.uber.org/mock/gomock"
)

// MockSynthesizer is a mock of Synthesizer interface.
type MockSynthesizer struct {
	ctrl     *gomock.Controller
	recorder *MockSynthesizerMockRecorder
	isgomock struct{}
}

// MockSynthesizerMockRecorder is the mock recorder for MockSynthesizer.
type MockSynthesizerMockRecorder struct {
	mock *MockSynthesizer
}

// NewMockSynthesizer creates a new mock instance.
func NewMockSynthesizer(ctrl *gomock.Controller) *MockSynthesizer {
	mock := &MockSynthesizer{ctrl: ctrl}
	mock.recorder = &MockSynthesizerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSynthesizer) EXPECT() *MockSynthesizerMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockSynthesizer) Close(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockSynthesizerMockRecorder) Close(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockSynthesizer)(nil).Close), ctx)
}

// SampleRate mocks base method.
func (m *MockSynthesizer) SampleRate() int32 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SampleRate")
	ret0, _ := ret[0].(int32)
	return ret0
}

// SampleRate indicates an expected call of SampleRate.
func (mr *MockSynthesizerMockRecorder) SampleRate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SampleRate", reflect.TypeOf((*MockSynthesizer)(nil).SampleRate))
}

// Synthesize mocks base method.
func (m *MockSynthesizer) Synthesize(ctx context.Context, tokens <-chan core.Token, arg2 chan<- core.AudioFrame) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Synthesize", ctx, tokens, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// Synthesize indicates an expected call of Synthesize.
func (mr *MockSynthesizerMockRecorder) Synthesize(ctx, tokens, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Synthesize", reflect.TypeOf((*MockSynthesizer)(nil).Synthesize), ctx, tokens, arg2)
}

// MockBrain is a mock of Brain interface.
type MockBrain struct {
	ctrl     *gomock.Controller
	recorder *MockBrainMockRecorder
	isgomock struct{}
}

// MockBrainMockRecorder is the mock recorder for MockBrain.
type MockBrainMockRecorder struct {
	mock *MockBrain
}

// NewMockBrain creates a new mock instance.
func NewMockBrain(ctrl *gomock.Controller) *MockBrain {
	mock := &MockBrain{ctrl: ctrl}
	mock.recorder = &MockBrainMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBrain) EXPECT() *MockBrainMockRecorder {
	return m.recorder
}

// Generate mocks base method.
func (m *MockBrain) Generate(ctx context.Context, prompt string, tools dialog.Tools, tokens chan<- core.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Generate", ctx, prompt, tools, tokens)
	ret0, _ := ret[0].(error)
	return ret0
}

// Generate indicates an expected call of Generate.
func (mr *MockBrainMockRecorder) Generate(ctx, prompt, tools, tokens any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Generate", reflect.TypeOf((*MockBrain)(nil).Generate), ctx, prompt, tools, tokens)
}

// MockTools is a mock of Tools interface.
type MockTools struct {
	ctrl     *gomock.Controller
	recorder *MockToolsMockRecorder
	isgomock struct{}
}

// MockToolsMockRecorder is the mock recorder for MockTools.
type MockToolsMockRecorder struct {
	mock *MockTools
}

// NewMockTools creates a new mock instance.
func NewMockTools(ctrl *gomock.Controller) *MockTools {
	mock := &MockTools{ctrl: ctrl}
	mock.recorder = &MockToolsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTools) EXPECT() *MockToolsMockRecorder {
	return m.recorder
}

// AddFiller mocks base method.
func (m *MockTools) AddFiller(token core.Token) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddFiller", token)
}

// AddFiller indicates an expected call of AddFiller.
func (mr *MockToolsMockRecorder) AddFiller(token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddFiller", reflect.TypeOf((*MockTools)(nil).AddFiller), token)
}

// PlayAudio mocks base method.
func (m *MockTools) PlayAudio(wave *audio.Wave, opts *audio.Options) (audio.Handle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PlayAudio", wave, opts)
	ret0, _ := ret[0].(audio.Handle)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PlayAudio indicates an expected call of PlayAudio.
func (mr *MockToolsMockRecorder) PlayAudio(wave, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PlayAudio", reflect.TypeOf((*MockTools)(nil).PlayAudio), wave, opts)
}

// SetInterruptible mocks base method.
func (m *MockTools) SetInterruptible(interruptible bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetInterruptible", interruptible)
}

// SetInterruptible indicates an expected call of SetInterruptible.
func (mr *MockToolsMockRecorder) SetInterruptible(interruptible any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetInterruptible", reflect.TypeOf((*MockTools)(nil).SetInterruptible), interruptible)
}
